### ISSUE TITLE
run time exception - Segmentation fault 

### ISSUE THREAD

**Issue by amesh90** [yan-lu/LineSLAM#3]
I've successfully compiled and built your code but when trying to run the test on a bag file it crashed with this error  @yan-lu 

`**\* glibc detected **\* /home/amira/lineslam_catkin_ws5/devel/lib/lineslam/lineslam: free(): corrupted unsorted chunks: 0x00007fff9414dbc0 ***
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
singular matrix A for dgetrf_ in dAx_eq_b_LU()

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb2255700 (LWP 9365)]
0x00007fffee52d67e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fffee52d67e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffee5300b5 in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000712459 in dAx_eq_b_LU ()
#3  0x0000000000710f8b in dlevmar_dif ()
#4  0x00000000006abf3e in MLEstimateLine3d (line=..., maxIter=100)

```
at /home/amira/lineslam_catkin_ws5/src/LineSLAM-master/src/line/utils.cpp:1036
```
#5  0x000000000068206c in Node::detect3DLines(cv::Mat const&, cv::Mat const&, double, cv::Mat const&, double, double, double, std::string) [clone ._omp_fn.3]

```
()
at /home/amira/lineslam_catkin_ws5/src/LineSLAM-master/src/line/lineslam.cpp:347
```
#6  0x0000000000687d25 in Node::detect3DLines (this=<optimized out>,

```
gray_uchar=..., depth_float=..., line2d_len_thres=6.9532764444007662e-310, 
K=..., ratio_of_collinear_pts=<optimized out>, 
line_3d_len_thres_m=<optimized out>, depth_scaling=<optimized out>, 
algorithm=...)
at /home/amira/lineslam_catkin_ws5/src/LineSLAM-master/src/line/lineslam.cpp:344
```
#7  0x0000000000587638 in operator() (a8=..., a7=1, a4=..., p=0x7fffa421fff0,

```
this=0x7fffa4245f50, a6=0.02, a5=0.59999999999999998, a3=10, a2=..., 
a1=...) at /usr/include/boost/bind/mem_fn_template.hpp:958
```
#8  operator()<boost::_mfi::mf8<void, Node, const cv::Mat&, const cv::Mat&, doub

(gdb) 
`

**Comment by lizhihuit** [comment]
can i use the version of ros-indigo,thx

**Comment by lizhihuit** [comment]
@amesh90  must  ros-hydro?
